#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Wed Sep 10 16:52:32 2025
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from SettingsDialogBase import SettingsDialogBase


class App(wx.App):
    def OnInit(self):
        self.settingsdlg = SettingsDialogBase(None, wx.ID_ANY, "")
        self.SetTopWindow(self.settingsdlg)
        self.settingsdlg.ShowModal()
        self.settingsdlg.Destroy()
        return True

# end of class App

if __name__ == "__main__":
    app = App(0)
    app.MainLoop()
