# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Wed Sep 10 12:45:44 2025
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# Dialog確認用のダミー
# end wxGlade


class DummyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: DummyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((200, 200))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        self.button_settingdlg = wx.Button(self.panel_1, wx.ID_ANY, u"環境設定...")
        sizer_2.Add(self.button_settingdlg, 1, wx.ALL | wx.EXPAND, 8)

        self.button_periodicdlg = wx.Button(self.panel_1, wx.ID_ANY, u"定期実行設定...")
        sizer_2.Add(self.button_periodicdlg, 1, wx.ALL | wx.EXPAND, 8)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        self.Centre()

        self.button_settingdlg.Bind(wx.EVT_BUTTON, self.on_open_settings_dlg)
        self.button_periodicdlg.Bind(wx.EVT_BUTTON, self.on_open_periodic_setteings_dlg)
        # end wxGlade

    def on_open_settings_dlg(self, event):  # wxGlade: DummyFrame.<event_handler>
        print("Event handler 'on_open_settings_dlg' not implemented!")
        event.Skip()

    def on_open_periodic_setteings_dlg(self, event):  # wxGlade: DummyFrame.<event_handler>
        print("Event handler 'on_open_periodic_setteings_dlg' not implemented!")
        event.Skip()

# end of class DummyFrame
