# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Wed Sep 10 12:45:44 2025
#
# fmt: off
# ruff: noqa: I001, PGH003, PLR0915, E501, FBT003, UP025
# ruff: noqa: ANN001, ANN002, ANN003, ANN201, ANN204
# type: ignore

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class PeriodicDialogBase(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PeriodicDialogBase.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((400, 240))
        self.SetTitle(u"定期実行設定")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 2)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_4, 0, wx.ALL | wx.EXPAND, 4)

        label_1 = wx.StaticText(self, wx.ID_ANY, u"保存先: ")
        sizer_4.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.text_ctrl_periodic_folder = wx.TextCtrl(self, wx.ID_ANY, "")
        sizer_4.Add(self.text_ctrl_periodic_folder, 1, wx.ALIGN_CENTER_VERTICAL, 0)

        self.button_periodic_folder_brows = wx.Button(self, wx.ID_ANY, "...")
        self.button_periodic_folder_brows.SetMinSize((25, 23))
        sizer_4.Add(self.button_periodic_folder_brows, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 4)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_5, 0, wx.ALL | wx.EXPAND, 4)

        label_2 = wx.StaticText(self, wx.ID_ANY, u"間　隔: ")
        sizer_5.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL, 4)

        self.spin_ctrl_periodic_interval = wx.SpinCtrl(self, wx.ID_ANY, "3", min=1, max=3600, style=wx.ALIGN_RIGHT | wx.SP_ARROW_KEYS)
        sizer_5.Add(self.spin_ctrl_periodic_interval, 0, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.TOP, 4)

        label_3 = wx.StaticText(self, wx.ID_ANY, u"秒")
        sizer_5.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 4)

        label_4 = wx.StaticText(self, wx.ID_ANY, u"終了キー: ")
        sizer_5.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 24)

        self.choice_periodic_stopkey_modifire = wx.Choice(self, wx.ID_ANY, choices=["none", "Shift", "Ctrl", "Alt"])
        self.choice_periodic_stopkey_modifire.SetSelection(0)
        sizer_5.Add(self.choice_periodic_stopkey_modifire, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_6 = wx.StaticText(self, wx.ID_ANY, "+")
        sizer_5.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 4)

        self.choice_periodic_stop_fkey = wx.Choice(self, wx.ID_ANY, choices=["F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12"])
        self.choice_periodic_stop_fkey.SetSelection(10)
        sizer_5.Add(self.choice_periodic_stop_fkey, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_6, 1, wx.ALL | wx.EXPAND, 4)

        sizer_7 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"対象"), wx.VERTICAL)
        sizer_6.Add(sizer_7, 0, wx.EXPAND, 0)

        self.choice_periodic_capture_target = wx.Choice(sizer_7.GetStaticBox(), wx.ID_ANY, choices=[u"デスクトップ", u"アクティブウィンドウ"])
        self.choice_periodic_capture_target.SetSelection(0)
        sizer_7.Add(self.choice_periodic_capture_target, 0, wx.ALL, 4)

        sizer_8 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"ナンバリング"), wx.VERTICAL)
        sizer_6.Add(sizer_8, 0, wx.EXPAND | wx.LEFT, 4)

        self.radio_btn_periodic_numbering_datetime = wx.RadioButton(sizer_8.GetStaticBox(), wx.ID_ANY, u"日時 (yyyymmdd_hhmmss)", style=wx.RB_GROUP)
        self.radio_btn_periodic_numbering_datetime.SetValue(1)
        sizer_8.Add(self.radio_btn_periodic_numbering_datetime, 0, wx.ALL, 4)

        self.radio_btn_periodic_numbering_autosave = wx.RadioButton(sizer_8.GetStaticBox(), wx.ID_ANY, u"自動保存の設定に従う")
        sizer_8.Add(self.radio_btn_periodic_numbering_autosave, 0, wx.ALL, 4)

        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_6.Add(sizer_9, 1, wx.EXPAND, 0)

        self.button_periodic_start = wx.Button(self, wx.ID_EXECUTE, u"開始")
        self.button_periodic_start.Enable(False)
        sizer_9.Add(self.button_periodic_start, 1, wx.ALL | wx.EXPAND, 4)

        self.button_periodic_stop = wx.Button(self, wx.ID_STOP, u"終了")
        self.button_periodic_stop.Enable(False)
        sizer_9.Add(self.button_periodic_stop, 0, wx.ALL | wx.EXPAND, 4)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        self.SetSizer(sizer_1)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()
        self.Centre()

        self.button_periodic_folder_brows.Bind(wx.EVT_BUTTON, self.on_save_folder_browse)
        self.button_periodic_start.Bind(wx.EVT_BUTTON, self.on_periodic_capture_ctrl)
        self.button_periodic_stop.Bind(wx.EVT_BUTTON, self.on_periodic_capture_ctrl)
        # end wxGlade

    def on_save_folder_browse(self, event):  # wxGlade: PeriodicDialogBase.<event_handler>
        print("Event handler 'on_save_folder_browse' not implemented!")
        event.Skip()

    def on_periodic_capture_ctrl(self, event):  # wxGlade: PeriodicDialogBase.<event_handler>
        print("Event handler 'on_periodic_capture_ctrl' not implemented!")
        event.Skip()

# end of class PeriodicDialogBase
