# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Wed Sep 10 12:45:44 2025
#
# fmt: off
# ruff: noqa: I001, PGH003, PLR0915, E501, FBT003, UP025
# ruff: noqa: ANN001, ANN002, ANN003, ANN201, ANN204
# type: ignore

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class SettingsDialogBase(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SettingsDialogBase.__init__
        # Button Event ID's
        self.BTN_ID_ADD  = 1001
        self.BTN_ID_DEL  = 1002
        self.BTN_ID_UP   = 1003
        self.BTN_ID_DOWN = 1004
        self.BTN_ID_BMP_CTRL_ALT   = 1101
        self.BTN_ID_BMP_CTRL_SHIFT = 1102
        self.BTN_ID_PNG_CTRL_ALT   = 1103
        self.BTN_ID_PNG_CTRL_SHIFT = 1104
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((400, 400))
        self.SetTitle(u"環境設定")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)

        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_1, u"基本設定")

        sizer_3 = wx.BoxSizer(wx.VERTICAL)

        self.panel_1 = wx.Panel(self.notebook_1_pane_1, wx.ID_ANY)
        sizer_3.Add(self.panel_1, 2, wx.ALL | wx.EXPAND, 2)

        sizer_4 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, u"保存先"), wx.VERTICAL)

        self.radio_btn_inquire_allways = wx.RadioButton(sizer_4.GetStaticBox(), wx.ID_ANY, u"保存ファイルを毎回指定する", style=wx.RB_GROUP)
        sizer_4.Add(self.radio_btn_inquire_allways, 0, wx.EXPAND | wx.LEFT, 4)

        self.radio_btn_auto_save = wx.RadioButton(sizer_4.GetStaticBox(), wx.ID_ANY, u"ファイル自動保存")
        sizer_4.Add(self.radio_btn_auto_save, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.TOP, 4)

        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(sizer_15, 1, wx.EXPAND, 0)

        self.list_box_auto_save_folders = wx.ListBox(sizer_4.GetStaticBox(), wx.ID_ANY, choices=[], style=wx.LB_NEEDED_SB | wx.LB_SINGLE)
        sizer_15.Add(self.list_box_auto_save_folders, 1, wx.ALL | wx.EXPAND, 2)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(sizer_5, 0, wx.ALL | wx.EXPAND, 2)

        self.button_add_folder = wx.Button(sizer_4.GetStaticBox(), self.BTN_ID_ADD, u"追加")
        sizer_5.Add(self.button_add_folder, 0, 0, 0)

        self.button_del_folder = wx.Button(sizer_4.GetStaticBox(), self.BTN_ID_DEL, u"削除")
        sizer_5.Add(self.button_del_folder, 0, 0, 0)

        sizer_5.Add((20, 20), 1, wx.ALIGN_CENTER_VERTICAL, 0)

        self.button_up_folder = wx.Button(sizer_4.GetStaticBox(), self.BTN_ID_UP, u"△")
        sizer_5.Add(self.button_up_folder, 0, 0, 0)

        self.button_down_folder = wx.Button(sizer_4.GetStaticBox(), self.BTN_ID_DOWN, u"▽")
        sizer_5.Add(self.button_down_folder, 0, 0, 0)

        self.panel_2 = wx.Panel(self.notebook_1_pane_1, wx.ID_ANY)
        sizer_3.Add(self.panel_2, 0, wx.ALL | wx.EXPAND, 2)

        sizer_6 = wx.StaticBoxSizer(wx.StaticBox(self.panel_2, wx.ID_ANY, u"ナンバリング"), wx.VERTICAL)

        self.radio_btn_numbering_datetime = wx.RadioButton(sizer_6.GetStaticBox(), wx.ID_ANY, u"日時 (yyyymmdd_hhmmss)", style=wx.RB_GROUP)
        sizer_6.Add(self.radio_btn_numbering_datetime, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT, 4)

        self.radio_btn_nubering_prefix_sequence = wx.RadioButton(sizer_6.GetStaticBox(), wx.ID_ANY, u"接頭語+シーケンス番号")
        sizer_6.Add(self.radio_btn_nubering_prefix_sequence, 0, wx.EXPAND | wx.LEFT, 4)

        sizer_7 = wx.StaticBoxSizer(wx.StaticBox(sizer_6.GetStaticBox(), wx.ID_ANY, ""), wx.HORIZONTAL)
        sizer_6.Add(sizer_7, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT, 4)

        label_2 = wx.StaticText(sizer_7.GetStaticBox(), wx.ID_ANY, u"接頭語: ")
        sizer_7.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.text_ctrl_prefix = wx.TextCtrl(sizer_7.GetStaticBox(), wx.ID_ANY, "")
        self.text_ctrl_prefix.SetMinSize((49, 23))
        sizer_7.Add(self.text_ctrl_prefix, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_3 = wx.StaticText(sizer_7.GetStaticBox(), wx.ID_ANY, u"シーケンス桁数: ")
        sizer_7.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 12)

        self.spin_ctrl_sequence_digits = wx.SpinCtrl(sizer_7.GetStaticBox(), wx.ID_ANY, "6", min=1, max=6, style=wx.ALIGN_RIGHT | wx.SP_ARROW_KEYS)
        self.spin_ctrl_sequence_digits.SetMinSize((40, 23))
        sizer_7.Add(self.spin_ctrl_sequence_digits, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_4 = wx.StaticText(sizer_7.GetStaticBox(), wx.ID_ANY, u"開始番号: ")
        sizer_7.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 12)

        self.spin_ctrl_sequence_begin = wx.SpinCtrl(sizer_7.GetStaticBox(), wx.ID_ANY, "0", min=0, max=100, style=wx.ALIGN_RIGHT | wx.SP_ARROW_KEYS)
        self.spin_ctrl_sequence_begin.SetMinSize((48, 23))
        sizer_7.Add(self.spin_ctrl_sequence_begin, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_2, u"その他の設定")

        sizer_9 = wx.BoxSizer(wx.VERTICAL)

        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9.Add(sizer_18, 1, wx.EXPAND, 0)

        self.checkbox_capture_mcursor = wx.CheckBox(self.notebook_1_pane_2, wx.ID_ANY, u"マウスカーソルをキャプチャーする")
        self.checkbox_capture_mcursor.Enable(False)
        sizer_18.Add(self.checkbox_capture_mcursor, 1, wx.ALL | wx.EXPAND, 4)

        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9.Add(sizer_19, 1, wx.EXPAND, 0)

        self.checkbox_sound_on_capture = wx.CheckBox(self.notebook_1_pane_2, wx.ID_ANY, u"キャプチャー終了時に音を鳴らす")
        sizer_19.Add(self.checkbox_sound_on_capture, 1, wx.ALL | wx.EXPAND, 4)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9.Add(sizer_8, 1, wx.EXPAND, 0)

        self.checkbox_delayed_capture = wx.CheckBox(self.notebook_1_pane_2, wx.ID_ANY, u"遅延キャプチャー")
        self.checkbox_delayed_capture.SetMinSize((89, 15))
        sizer_8.Add(self.checkbox_delayed_capture, 0, wx.ALL | wx.EXPAND, 4)

        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_10, 0, wx.EXPAND, 0)

        self.spin_ctrl_delayed_time = wx.SpinCtrl(self.notebook_1_pane_2, wx.ID_ANY, "5", min=1, max=60, style=wx.ALIGN_RIGHT | wx.SP_ARROW_KEYS)
        self.spin_ctrl_delayed_time.SetMinSize((44, 23))
        sizer_10.Add(self.spin_ctrl_delayed_time, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_5 = wx.StaticText(self.notebook_1_pane_2, wx.ID_ANY, u"秒後")
        sizer_10.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 4)

        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9.Add(sizer_11, 1, wx.EXPAND, 0)

        self.checkbox_trimming = wx.CheckBox(self.notebook_1_pane_2, wx.ID_ANY, u"トリミング")
        self.checkbox_trimming.SetMinSize((68, 15))
        sizer_11.Add(self.checkbox_trimming, 0, wx.ALL | wx.EXPAND, 4)

        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11.Add(sizer_12, 0, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.notebook_1_pane_2, wx.ID_ANY, u"上: ")
        sizer_12.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 4)

        self.spin_ctrl_trimming_top = wx.SpinCtrl(self.notebook_1_pane_2, wx.ID_ANY, "0", min=0, max=100, style=wx.ALIGN_RIGHT | wx.SP_ARROW_KEYS)
        sizer_12.Add(self.spin_ctrl_trimming_top, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_7 = wx.StaticText(self.notebook_1_pane_2, wx.ID_ANY, u"下: ")
        sizer_12.Add(label_7, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 4)

        self.spin_ctrl_trimming_bottom = wx.SpinCtrl(self.notebook_1_pane_2, wx.ID_ANY, "0", min=0, max=100, style=wx.ALIGN_RIGHT | wx.SP_ARROW_KEYS)
        sizer_12.Add(self.spin_ctrl_trimming_bottom, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_8 = wx.StaticText(self.notebook_1_pane_2, wx.ID_ANY, u"左: ")
        sizer_12.Add(label_8, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 4)

        self.spin_ctrl_trimming_left = wx.SpinCtrl(self.notebook_1_pane_2, wx.ID_ANY, "0", min=0, max=100, style=wx.ALIGN_RIGHT | wx.SP_ARROW_KEYS)
        sizer_12.Add(self.spin_ctrl_trimming_left, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_9 = wx.StaticText(self.notebook_1_pane_2, wx.ID_ANY, u"右: ")
        sizer_12.Add(label_9, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 4)

        self.spin_ctrl_trimming_right = wx.SpinCtrl(self.notebook_1_pane_2, wx.ID_ANY, "0", min=0, max=100, style=wx.ALIGN_RIGHT | wx.SP_ARROW_KEYS)
        sizer_12.Add(self.spin_ctrl_trimming_right, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_20 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_2, wx.ID_ANY, u"ホット・キー"), wx.HORIZONTAL)
        sizer_9.Add(sizer_20, 1, wx.EXPAND | wx.RIGHT | wx.TOP, 2)

        sizer_21 = wx.StaticBoxSizer(wx.StaticBox(sizer_20.GetStaticBox(), wx.ID_ANY, u"修飾キー"), wx.HORIZONTAL)
        sizer_20.Add(sizer_21, 1, wx.EXPAND, 0)

        sizer_23 = wx.StaticBoxSizer(wx.StaticBox(sizer_21.GetStaticBox(), wx.ID_ANY, u"クリップボードコピー"), wx.VERTICAL)
        sizer_21.Add(sizer_23, 0, wx.EXPAND, 0)

        self.radio_btn_hotkey_bmp_ctrl_alt = wx.RadioButton(sizer_23.GetStaticBox(), self.BTN_ID_BMP_CTRL_ALT, "Ctrl+Alt", style=wx.RB_GROUP)
        self.radio_btn_hotkey_bmp_ctrl_alt.SetValue(1)
        sizer_23.Add(self.radio_btn_hotkey_bmp_ctrl_alt, 1, 0, 0)

        self.radio_btn_hotkey_bmp_ctrl_shift = wx.RadioButton(sizer_23.GetStaticBox(), self.BTN_ID_BMP_CTRL_SHIFT, "Ctrl+Shift")
        sizer_23.Add(self.radio_btn_hotkey_bmp_ctrl_shift, 1, 0, 0)

        sizer_24 = wx.StaticBoxSizer(wx.StaticBox(sizer_21.GetStaticBox(), wx.ID_ANY, u"PNG保存"), wx.VERTICAL)
        sizer_21.Add(sizer_24, 0, wx.EXPAND | wx.LEFT, 4)

        self.radio_btn_hotkey_png_ctrl_alt = wx.RadioButton(sizer_24.GetStaticBox(), self.BTN_ID_PNG_CTRL_ALT, "Ctrl+Alt", style=wx.RB_GROUP)
        sizer_24.Add(self.radio_btn_hotkey_png_ctrl_alt, 1, 0, 0)

        self.radio_btn_hotkey_png_ctrl_shift = wx.RadioButton(sizer_24.GetStaticBox(), self.BTN_ID_PNG_CTRL_SHIFT, "Ctrl+Shift")
        self.radio_btn_hotkey_png_ctrl_shift.SetValue(1)
        sizer_24.Add(self.radio_btn_hotkey_png_ctrl_shift, 1, 0, 0)

        sizer_22 = wx.StaticBoxSizer(wx.StaticBox(sizer_20.GetStaticBox(), wx.ID_ANY, u"ターゲット"), wx.VERTICAL)
        sizer_20.Add(sizer_22, 1, wx.EXPAND | wx.LEFT, 4)

        grid_sizer_3 = wx.FlexGridSizer(3, 2, 1, 1)
        sizer_22.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_12 = wx.StaticText(sizer_22.GetStaticBox(), wx.ID_ANY, u"デスクトップ: ")
        grid_sizer_3.Add(label_12, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.TOP, 2)

        label_13 = wx.StaticText(sizer_22.GetStaticBox(), wx.ID_ANY, "0")
        grid_sizer_3.Add(label_13, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_14 = wx.StaticText(sizer_22.GetStaticBox(), wx.ID_ANY, u"ディスプレイ: ")
        grid_sizer_3.Add(label_14, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.TOP, 2)

        label_15 = wx.StaticText(sizer_22.GetStaticBox(), wx.ID_ANY, u"1 ～")
        grid_sizer_3.Add(label_15, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_16 = wx.StaticText(sizer_22.GetStaticBox(), wx.ID_ANY, u"アクティブウィンドウ: ")
        grid_sizer_3.Add(label_16, 0, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.LEFT | wx.TOP, 2)

        self.choice_hotkey_active_window = wx.Choice(sizer_22.GetStaticBox(), wx.ID_ANY, choices=["F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12"])
        self.choice_hotkey_active_window.SetSelection(8)
        grid_sizer_3.Add(self.choice_hotkey_active_window, 0, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM, 2)

        sizer_9.Add((20, 8), 1, wx.EXPAND, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        self.notebook_1_pane_2.SetSizer(sizer_9)

        self.panel_2.SetSizer(sizer_6)

        self.panel_1.SetSizer(sizer_4)

        self.notebook_1_pane_1.SetSizer(sizer_3)

        self.SetSizer(sizer_1)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()
        self.Centre()

        self.button_add_folder.Bind(wx.EVT_BUTTON, self.on_save_folder_add)
        self.button_del_folder.Bind(wx.EVT_BUTTON, self.on_save_folder_del)
        self.button_up_folder.Bind(wx.EVT_BUTTON, self.on_save_folder_move)
        self.button_down_folder.Bind(wx.EVT_BUTTON, self.on_save_folder_move)
        self.radio_btn_hotkey_bmp_ctrl_alt.Bind(wx.EVT_RADIOBUTTON, self.on_btn_hotkey_change)
        self.radio_btn_hotkey_bmp_ctrl_shift.Bind(wx.EVT_RADIOBUTTON, self.on_btn_hotkey_change)
        self.radio_btn_hotkey_png_ctrl_alt.Bind(wx.EVT_RADIOBUTTON, self.on_btn_hotkey_change)
        self.radio_btn_hotkey_png_ctrl_shift.Bind(wx.EVT_RADIOBUTTON, self.on_btn_hotkey_change)
        # end wxGlade

    def on_save_folder_add(self, event):  # wxGlade: SettingsDialogBase.<event_handler>
        print("Event handler 'on_save_folder_add' not implemented!")
        event.Skip()

    def on_save_folder_del(self, event):  # wxGlade: SettingsDialogBase.<event_handler>
        print("Event handler 'on_save_folder_del' not implemented!")
        event.Skip()

    def on_save_folder_move(self, event):  # wxGlade: SettingsDialogBase.<event_handler>
        print("Event handler 'on_save_folder_move' not implemented!")
        event.Skip()

    def on_btn_hotkey_change(self, event):  # wxGlade: SettingsDialogBase.<event_handler>
        print("Event handler 'on_btn_hotkey_change' not implemented!")
        event.Skip()

# end of class SettingsDialogBase
