#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0b1 on Fri Aug 30 19:02:21 2024
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class SettingsDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SettingsDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("Settings")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)

        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_1, u"基本設定")

        sizer_3 = wx.BoxSizer(wx.VERTICAL)

        sizer_4 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, u"保存設定"), wx.HORIZONTAL)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)

        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add(sizer_5, 1, wx.EXPAND, 0)

        self.radio_btn_1 = wx.RadioButton(self.notebook_1_pane_1, wx.ID_ANY, u"ファイル自動保存")
        sizer_5.Add(self.radio_btn_1, 0, 0, 0)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add(sizer_6, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, u"保存先: ")
        sizer_6.Add(label_1, 0, 0, 0)

        self.list_box_1 = wx.ListBox(self.notebook_1_pane_1, wx.ID_ANY, choices=["choice 1"])
        sizer_6.Add(self.list_box_1, 1, 0, 0)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add(sizer_7, 1, wx.EXPAND, 0)

        sizer_7.Add((41, 20), 0, 0, 0)

        self.button_1 = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, u"追加")
        self.button_1.SetMinSize((49, 23))
        sizer_7.Add(self.button_1, 0, 0, 0)

        self.button_2 = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, u"削除")
        self.button_2.SetMinSize((49, 23))
        sizer_7.Add(self.button_2, 0, 0, 0)

        sizer_7.Add((20, 20), 1, 0, 0)

        self.button_3 = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, u"△")
        self.button_3.SetMinSize((41, 23))
        sizer_7.Add(self.button_3, 0, 0, 0)

        self.button_4 = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, u"▽")
        self.button_4.SetMinSize((41, 23))
        sizer_7.Add(self.button_4, 0, 0, 0)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add(sizer_8, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, u"接頭語: ")
        sizer_8.Add(label_2, 0, 0, 0)

        self.text_ctrl_1 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "SS")
        self.text_ctrl_1.SetMinSize((65, 23))
        sizer_8.Add(self.text_ctrl_1, 0, 0, 0)

        label_3 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, u"シーケンス桁数: ")
        sizer_8.Add(label_3, 0, 0, 0)

        self.spin_ctrl_1 = wx.SpinCtrl(self.notebook_1_pane_1, wx.ID_ANY, "6", min=1, max=6)
        sizer_8.Add(self.spin_ctrl_1, 0, wx.ALL, 1)

        label_4 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, u"開始番号: ")
        sizer_8.Add(label_4, 0, 0, 0)

        self.spin_ctrl_2 = wx.SpinCtrl(self.notebook_1_pane_1, wx.ID_ANY, "0", min=0, max=100000)
        sizer_8.Add(self.spin_ctrl_2, 0, 0, 0)

        self.radio_btn_2 = wx.RadioButton(self.notebook_1_pane_1, wx.ID_ANY, u"保存ファイル名を毎回指定する")
        sizer_5.Add(self.radio_btn_2, 0, 0, 0)

        self.cb_mcursor = wx.CheckBox(self.notebook_1_pane_1, wx.ID_ANY, u"マウスカーソルをキャプチャする")
        sizer_3.Add(self.cb_mcursor, 0, wx.ALL, 4)

        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_2, u"ホット・キー")

        sizer_9 = wx.BoxSizer(wx.VERTICAL)

        sizer_10 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_2, wx.ID_ANY, u"クリップボードへコピー"), wx.VERTICAL)
        sizer_9.Add(sizer_10, 1, wx.EXPAND, 0)

        sizer_10.Add((0, 0), 0, 0, 0)

        sizer_11 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_2, wx.ID_ANY, u"PNGで保存"), wx.VERTICAL)
        sizer_9.Add(sizer_11, 1, wx.EXPAND, 0)

        sizer_11.Add((0, 0), 0, 0, 0)

        self.notebook_1_pane_3 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_3, u"トリミング")

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        self.notebook_1_pane_2.SetSizer(sizer_9)

        self.notebook_1_pane_1.SetSizer(sizer_3)

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()
        # end wxGlade

# end of class SettingsDialog

class MyApp(wx.App):
    def OnInit(self):
        self.settingsdlg = SettingsDialog(None, wx.ID_ANY, "")
        self.SetTopWindow(self.settingsdlg)
        self.settingsdlg.ShowModal()
        self.settingsdlg.Destroy()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
