#----------------------------------------------------------------------
# This file was generated by .\make_resource_file.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
index = []

get_icon_help = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAGoSURBVDhPrZJNK21RGMfX3mEoFKU7'
    b'vUxIYaAMDJTiE9wMOOpEh2/g7eJIPoLDuXQO6jA0YGaqKJShly8gDiOJ2vv+/msvKyd3dv3r'
    b't5/1rOdl7bV6zP8qcLZCY+OZ6jgynSxbQTk3JjYXxa3cm+Kf9aVBKp0ZxvyGeniEGBqhDNni'
    b'Zq6E9QqdtaJ4HrMD+9BG/15sH7TDHuy4HC/fgMAvzCwMcsoidoTDL7FXMMXekmIw63Kt7BVS'
    b'6ckakpVYUiIJLawPIQsvsA39xM6ILbDmmkFHcXPtzf1B3M2nAfLWC+M7TA8Fu9hTeIUqkJRD'
    b'rq3xV/gJ5ciE93K28+sRxU+cVot7AEf4J4q5HD2oanwDvXRc8aKJZqA+CEw6cX2Bzdfio+Ya'
    b'+K2oKXG9jmGi8Cf3nriSzdF1VZM0CEKj19ZvTcj/pGb4kSy9lFN2NUmDQt6eoBef494D2nMa'
    b'cli52BxkXU3lJJKgIdEsrMJGFJtn7YeBqcPo5GlY4UGXtS/9a5Q1JBoa3fNBe0ijrLFeoFhT'
    b'6vWlgTSazlQT6GKpgVLOLeZcg6P4N8qYv+Xdha/h1fOUAAAAAElFTkSuQmCC')
index.append('get_icon_help')
catalog['get_icon_help'] = get_icon_help

#----------------------------------------------------------------------
get_icon_settings = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAF+SURBVDhPtZI9L0NhFMfP7Y2xYTCY'
    b'upAIZRADGxFDBxOJkcYNyi7xEYTFREMqNdQoTSykCBuDRbUq8QEMBk1sUtfvPPfRl2gaifgn'
    b'v5xzz8tzzz3Plb/KsfaH5r1EN2YyeJKLw1Ty2foNClnbTDOwY5nWQDNVJ4h7iTZfJCoVyXNs'
    b'F5lTwudBlkl8icmnvIgrgzQV0qnkhyaqE9A8i7mjIE/zPX4Zdi1lE9McNbbWyEzA97ZjCnAN'
    b'N+DCHkyA6hKWoAKjMAZR9lI2E7iO/47JwBSUSGxjs3BiydpYCbQmY3tqO1AxSRGTggfQHdQr'
    b'BgPgcVi/iaBWt/ArmQPmvBWXt2/iRqDIG86wOc1Z5WxMJ4xorfZo4nuJHZhHuIJb0GXtczf2'
    b'R3L0OhdBm0ZgHPo49K26Aw6JYw7gCTpB/zyNqdLQA6/QCws0a6y2g5DjHGGGQz6L8mUIPwzL'
    b'lrDGTE5rglqjhluoFxOtYTaCJ1nnjVvWb1CrWziGVYv6/yGRLw4eb2ktvR12AAAAAElFTkSu'
    b'QmCC')
index.append('get_icon_settings')
catalog['get_icon_settings'] = get_icon_settings

#----------------------------------------------------------------------
get_icon_auto_save_folder = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAELSURBVDhPxZIxagJBFIZnFgNeIYVV'
    b'ICFaBa/hHVLsEgc8QcDSIn0KV3DB3CBHSJ3KKkWaFHuAlCFqXL83vFl0iYs2+sPHv/N29s3P'
    b'7DNnl1X3ivsustYURWFsNknXWq6Vb3Afuxb2DFcgH17AuzX2YZaNFzzvVWiQYE8wBGnQgEeY'
    b'wwgiCGnFv1+y9CMspIHD+hTvZC2ido29wiUspaaSZk3osf9NFkFR4lw4xfDyE+vCDXSUtpLD'
    b'Lfioe0WTH0zYEel+sUKetxMcJE1ZJj26QVXbDdbTNPWx6qR7yhkJd7CClv4N2VBGrCi8k7n5'
    b'k4LfyIfVQaqTpP6CAZec75wURlmX/+qYMT+FjNkAe/JKgbC3YnsAAAAASUVORK5CYII=')
index.append('get_icon_auto_save_folder')
catalog['get_icon_auto_save_folder'] = get_icon_auto_save_folder

#----------------------------------------------------------------------
menu_icon_open_folder = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFTSURBVDhPxZK/K0VhGMffc1A2s5Qy'
    b'GCQjBovBYrEoZdLt3B+nlNXCoJQddY7h3Nw7WSwWGZUio5uVgX9ASrcrjs/3veetIx2y8K1P'
    b'z3mfep7n+z7vMf8uL4tWQS30Pc+kaWq85CB+z9LfyjZYCcJhwj6MgAr74NozXvUwiTp8F8o1'
    b'qBB2YAPUoAfWoQXb4INzq/iEydtmEqW93ZwteGgkcdw92qZnhBM4hVflMqlZm5suES91cPJX'
    b'10I7Rbug2R37mOI4BhM5xmESH61ShZ1x0LSQUCU5Z1JzxPcg6CqOvFTzBnIfuStIHYpniNOw'
    b'CW3IO3RSsQZswX2+QQoLcI79XZspEI4XCY8895WboOIBmIVjJX7QMlw06/Gzc6Ata1mKo0wo'
    b'E/PunLSPfpiHkhJuifqR9mAI5ErPWiQ1vsFz0KjHL7aBU7nGM37KfNVvfvO/kDEfg0tdMzhi'
    b'0G8AAAAASUVORK5CYII=')
index.append('menu_icon_open_folder')
catalog['menu_icon_open_folder'] = menu_icon_open_folder

#----------------------------------------------------------------------
menu_icon_periodic_capture_settings = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAGrSURBVDhPrZLPK0RRFMfvm2zGShGy'
    b'oSyQREr4C5QFs2ClEMr4E5CyoWzRzPNjakbZEQplYWHhx0ITRYoFNspCfmxQZq7Pue8N7xl2'
    b'vvXpnHPvOefdc++z1B8aCId9e4u2rV3Xp18b9PSH8zDrkG8WlHqAUCJmPznhtwKu9SmdVs+Y'
    b'CMzALETTWr9gs/TXCZowXVADOXAGC2SfKK3qdEoll+LOSFknoHgKsweVsANbUA67FB9g41TJ'
    b'iEa+E1A8ghmFTubdNouu2GvFrMEye31mEX01IEG+mIRuElaIy/CL8Y9kX8RaB0ZGqU8s2tey'
    b'5h0hBDdS7ISqBHYpGu4dCMs9qGAqsIq5Y5Q2iUXeBhVw6bhGH5ALk1pLo8FCOx6Ri7uCWjDy'
    b'NniFoOMaZcZ7BL6s5WlFkvPmuP4G+9DAkQuc0DTYpLCRsaYTsfl3d68BJNfI22AD5I+bMJGV'
    b'Oras1/ZEbE6OnJHsSY7kGv18RvmB5O0lYdxK61syAtqySonHQC66xfsyvgYimsgFRaEa7mUN'
    b'FcE5DFF8alZcZTXIiEbNmConUhcUHrr+f0qpTydYhXVGzoFVAAAAAElFTkSuQmCC')
index.append('menu_icon_periodic_capture_settings')
catalog['menu_icon_periodic_capture_settings'] = menu_icon_periodic_capture_settings

#----------------------------------------------------------------------
menu_icon_copy_to_clipboard = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEzSURBVDhPtZI9SwNBEIb3THJgIdpb'
    b'C1ERLmBnoYV/Qyxs/AHprO3E+gojqJWVksrfIIkfIKK1hZVFwIAKfjzvuBv3jtj48cJzMzs7'
    b'M7t7u+63SrwtaHVtfQkzDe8W+JLyH6G918p7IVAQxTOYU7iDZ4hz3kDzWzTYUGBEH4nCMUhx'
    b'J+AJFknKajVnpKnLGDeIH8EUmKreStugFXdBKwm3k+flY2hsc9JgB2jcEwqG/h9UiMcNwqrf'
    b'FQ5V3OBH+tcGL96W9eqtKb6FWKOwwLU+YCsW+fy5ajoJ9wpI5R1UyLrFXsABtEH3Lo7hBOpw'
    b'CKa4gfzqfivvJ4lbxteLmysxC3UelJqZBlfGdjcxTbi2QPRYkPJ0hBWKw7wpnM9ljfkuaTe4'
    b'V9CBs4hu8C/PO33sX8m5D+cnTihglMZKAAAAAElFTkSuQmCC')
index.append('menu_icon_copy_to_clipboard')
catalog['menu_icon_copy_to_clipboard'] = menu_icon_copy_to_clipboard

#----------------------------------------------------------------------
menu_icon_save_to_png = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADzSURBVDhPYxhwwAilGeKTM+UZGP6X'
    b'A5kiQPwPLIgJmID4DVBb58K50x/CBKDgfxmQCAHiX2AudgCSA6oBqwUDFigNAqJAvGvh3Bkx'
    b'EC52EJ+csQRIgdSCAZILwM5GNhAXAKmBexHZALIA7QwA+pUdSrsCcRtYEAvAagBQQxKQWhSf'
    b'lCEHpGcAcSVQLAokhw7QDfgNVKgOpHuAOAyYSvYCaSWQBBBMhsr9hnAhANkAEPs/EL8AYlcg'
    b'NgDiCCDWh2I3IAbJgdTA9SFHGzCFgRPSJDAPN/AA4jUQJooLGDuBxGog5gRiUABiwyA5oBqw'
    b'2kEBGBgAsOcwgNpxL7oAAAAASUVORK5CYII=')
index.append('menu_icon_save_to_png')
catalog['menu_icon_save_to_png'] = menu_icon_save_to_png

#----------------------------------------------------------------------
menu_icon_exit = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFQSURBVDhPzVI7SgRBEK3aVfEAKhiZ'
    b'eQLBGwhiaqAgu+OOwY6IgYGeYRMDEWcDZ51dBAVNRdATCJ7AzEhQDyB+pnxV0zM2s5mJPnhd'
    b'Xa+ru6q6m/4c7Cw1w2iGSPYwnQAzE4dRA1+xrdNP4sdCcJBdDMvgu7kQwOpBuoYYizWMOKuY'
    b'BG/7SXctd4kajag+GMRfzjU0w/YpjMYavAqoDo7nUwtc51G5C8JoykkFNGlZWXmACB2A+86l'
    b'LKMzmCchuQpaUZmxivIAZpoFt5D5XFmr0THkT3BOWK6DVrtaicFv4VfwW3gAD3GJK0q0sAFZ'
    b'+71n4cW01322wAr8FrbBHecSWliFmWbipbQXv+TqMPwW9Lne8ikRqjiRD55Pk7iaWe/lJ7Gz'
    b'+mxHMPqRbkAtvfhI+rwFdPMCeIkEmyp4FXAHwwU4Zm5+uL9ZoWuIsdh/AaJvA+Jf+7WixC0A'
    b'AAAASUVORK5CYII=')
index.append('menu_icon_exit')
catalog['menu_icon_exit'] = menu_icon_exit

