#----------------------------------------------------------------------
# This file was generated by .\make_resource_file.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
index = []

get_icon_info = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAELSURBVDhPjdNNSgMxGMbx4CeCix5B'
    b'cCPaAxQPoIsepTfQO6iggtBVl912JerClbS7QgsVL+BSBDeKov9Hk+GddxLwgd8E3iRtJsmE'
    b'TPZwhjneolms7aKYDVzhC98F6jvHGmpR4Q5+whE2cWxqcoPaj1zCDkg0WVmH77vAb9r4hB8g'
    b'pRWI5mi/wmkseBNoqc+m5p0gLEzB6kDZRq5fdDrh3RSSJ6T04PuT1yUeuYxiqxzGtpjcK3Sh'
    b'LOMFvj+ZaQXX8JnGdgctfOBeBZdbPXLHuAJFG/iAAwxgx1THqPiLtIWUVfRh+6W6SIq/ykPo'
    b'Au1jHGtW4yor//2Y9M+NyTb+c9YGPsZa9c5/CeEHBV2TRDN1FLgAAAAASUVORK5CYII=')
index.append('get_icon_info')
catalog['get_icon_info'] = get_icon_info

#----------------------------------------------------------------------
get_icon_settings = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEBSURBVDhPpZOxTkJBEEUXTSikQSBW'
    b'foQN9ib+APSUtNIYQ4GtCS0fQm1NqcmLnSUNdDQUFCpBz4UZsixK8vAkh53M7gxM2A0HGOC3'
    b'+aJEHgo4RW+wwgvc49TWBl7iBJW7t5yjhmo0Qu3f4BW+Y6jjEnVgjmOLf1N7OqNYNdcYMksc'
    b'Y3bCxzOmfGIHq1ixWLmUbW0P484qSHnA+Mwj7vCBvqlvTSmj7y+UEBrB+bI1F95AI5Q24ZqW'
    b'rTFtW8UZbkd4Qv9prsa5w3NTcTyiq9rwFiXyqivw/4skdG1vsWj2MS3uou/rbBP/pIZ6QF6s'
    b'h6X3sEf8N8bM8HUTrhmiGiWE8AMSEHY8LvlZKwAAAABJRU5ErkJggg==')
index.append('get_icon_settings')
catalog['get_icon_settings'] = get_icon_settings

#----------------------------------------------------------------------
get_icon_quick_settings = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADFSURBVDhPpZNLDkFBEEWb2IKJ30bs'
    b'gMXYgcTeGIiJhIHvTLALzu10V1ozeBU3OUm9Sp/7PiGQCdzh5WQGHQiPtPCwgBGswJZjXTTM'
    b'EK4gzwqaZgAXkLPRwlMg+Qw6v4cuNC6QfIJSnsNXwRJ0QEJOH37J0asLdqBrvadKenBMO3ts'
    b'Yp4NKeXdVHJIcykr5tlQRCX5rkJPVcqKeTZUUckW1lDLSvRaaVA0exK9dhz/SFng+Sl/nH1C'
    b'/g5e5Ma/8y0tPOCE6RsboHhhK798bAAAAABJRU5ErkJggg==')
index.append('get_icon_quick_settings')
catalog['get_icon_quick_settings'] = get_icon_quick_settings

#----------------------------------------------------------------------
get_icon_auto_save_folder = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABwSURBVDhPY/z//z8DpUAPiJ8CMcgk'
    b'GP4JxL1ATBTYDcTImmH4HxBbADEITAPi30CMLP8AiNWAmCCwBmJkjch4OxAzHEESIBkzQhlk'
    b'AyYoTTYYNWCwGPAEwiQLPAYR7kAMStcYqYwABulxpzA7MzAAAEAAP81q/TMVAAAAAElFTkSu'
    b'QmCC')
index.append('get_icon_auto_save_folder')
catalog['get_icon_auto_save_folder'] = get_icon_auto_save_folder

#----------------------------------------------------------------------
get_icon_open_folder = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACLSURBVDhPY/z//z8DJYAJSlMEVID4'
    b'HhCDnALD/4B4DhATBbYDMbJmZGwDxHgBIxCDFJILjoMIdFvR8SUglgJinACbJmTsAsRFQPwH'
    b'SQyEfwFxPhAz8IMIAuAyECNrhuHrQMxwBEmAZExpIFKekKhiwHMIkyzwGkR4AfELIMYIIAL4'
    b'CRB7D3RuZGAAABPlUtiEJPnIAAAAAElFTkSuQmCC')
index.append('get_icon_open_folder')
catalog['get_icon_open_folder'] = get_icon_open_folder

#----------------------------------------------------------------------
get_icon_periodic_capture_settings = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEiSURBVDhPnZPLSgMxFEAHKT6oX6Ki'
    b'FlzoXvwHcam/okuf1PovrUvduCm0oB/gD/hY+KQ9ZyZTMtpY6YHTmdzcZJrkJhvDEp5gD1+D'
    b'fTzFZUyygJf4jYOE9l2huRVmsYMmveMZbmI96Lsx+8y5RseMuEA7HrFhIME6mmNu04C4ri90'
    b'dgff4RamWMM3dMyKgWN0Rv+FOPgZD/JWwTZ2i9ecc3SMG5vvtg3XWbKPxlp4iJ+4gyXm2n9v'
    b'4yk05m1EeCLG9chAxBwad9nJCdzlG7zFmoGIRXTMi41xS5hEuYT+DD9tI7AXnv9hNzytncox'
    b'es6TWMXKMUpcSH9NYg38KiT5Wcqe7waWpey7sWQpixfEizLVZYpxT/zaA35gfJ1Hay7IsiFc'
    b'j2EmnSFeNAAAAABJRU5ErkJggg==')
index.append('get_icon_periodic_capture_settings')
catalog['get_icon_periodic_capture_settings'] = get_icon_periodic_capture_settings

#----------------------------------------------------------------------
get_icon_copy_to_clipboard = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAB/SURBVDhPrZJRCoAgEESrj45R1DU7'
    b'ngjdymatgRY30+zBI6VFZ6IO7DC86KFJD2WgBJk14S1r3GkWyPcmzQmG69kEI85xp5ngvQLX'
    b'1NdWSGZrK8ghokrLOF8qhF8quHOZhTNmhRJGuEEVX5TTnkji1sJbsh+3OUHuPyj4uJ07ADiD'
    b'NQCA/U2eAAAAAElFTkSuQmCC')
index.append('get_icon_copy_to_clipboard')
catalog['get_icon_copy_to_clipboard'] = get_icon_copy_to_clipboard

#----------------------------------------------------------------------
get_icon_save_to_png = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACvSURBVDhPpZNLCsJAEERbjyGC11FX'
    b'3iSIeB3jnXSjq2QjHsD9WNWmoBOijs6DR39INzMkmZhZgkWULEjTLiEr2MAWLtnIRSfgIHN6'
    b'YyOD3gne5V/RCTbw3rlmY0AFH3Dn1Quf1YJPbKGuR/eQZC0YDkviUQWZwRM8wznk24hDUeJR'
    b'BYcvUA9c4QIeQy9KPKqIw1JL6tCTxGMsxtSSQ+hR4lHFP6Tin+mnL26MwgVmT0RUUDqUvIrk'
    b'AAAAAElFTkSuQmCC')
index.append('get_icon_save_to_png')
catalog['get_icon_save_to_png'] = get_icon_save_to_png

#----------------------------------------------------------------------
get_icon_exit = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACUSURBVDhPpZNRDkAwDIbHTZzDi1dO'
    b'4p48ugUR3MATf22VhW6KL/mSduuajc2AEo5wi0jzFRR5WsxOUIQL8iO7Q+NcIxKddDSwteEd'
    b'TQOfGdY2tLxtQLUrLI4MaBrQ9rmOXWCWuISgOATXXOlSF/yCtxQjeAR4Dmih2tcf0efTb1Rd'
    b'pM9X+fdjomfaQ2kRO0DhORuzAxXOWY8zs/H3AAAAAElFTkSuQmCC')
index.append('get_icon_exit')
catalog['get_icon_exit'] = get_icon_exit

# Image size
image_size=(16, 16)
